In [18]:
#Bibiotheken importieren 

import gym
import numpy as np
import random
from IPython.display import clear_output

In [19]:
#CliffWalking Umgebung von OpenAI gym aufsetzen 

env = gym.make('CliffWalking-v0', render_mode = "human")

In [20]:
#Zusandsvariablen für die Q - Tabelle ermitteln 

print (env.observation_space) #es gibt 48 Zustandsvariablen 
print (env.action_space) #es gibt 4 Aktionen

Discrete(48)
Discrete(4)


In [21]:
#Q - Tabelle mit Nullern gefüllt erstellen mit 48 Zeichen nach Zustandsvariablen und 4 Spalten nach Aktionen

q_table = np.zeros((48,4))
print(q_table)

#Parameter festlegen

alpha = 0.1 
gamma = 0.6
epsilon = 0.1
episoden = 10


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
for i in range(episoden):
    #Setzt den Status der Umgebung auf Anfang zurück
    state = env.reset()

    epochs, penalties, reward, = 0, 0, 0
    done = False

    print(state)
    
    while not done:
        #Prüft, ob ein Zufälliger Wert kleiner ist als der Epsilon Wert
        if random.uniform(0, 1) < epsilon:
            #Zufällige Aktion
            action = env.action_space.sample()
        else:
            #Beste Aktion aus Tabelle 
            action = np.argmax(q_table[state[0]])        

        #Nächsten Schritt definieren
        next_state_ = env.step(action)  
        
        next_state = next_state_[0]  
        reward = next_state_[1]  
        done = next_state_[2]  
        print(next_state_)
        
        #Zustand ersetzen mit Bellmann Gleichung 
        old_value = q_table[state[0], action]
        next_max = np.max(q_table[next_state])
        
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state[0], action] = new_value

        #Passt die Strafe an
        if reward == -10:
            penalties += 1

        #durchgeführte Schritte
        state = next_state
        epochs += 1

    #Löscht Output    
    if i % 100 == 0:
        clear_output(wait=True)
        print(f"Episode: {i}")

print("Training finished.\n")


(36, {'prob': 1})
(24, -1, False, False, {'prob': 1.0})


TypeError: 'int' object is not subscriptable

### Quellen

- Zelle 2,3: https://towardsdatascience.com/creating-a-custom-gym-environment-for-jupyter-notebooks-e17024474617
- Zelle 4,5: https://www.learndatasci.com/tutorials/reinforcement-q-learning-scratch-python-openai-gym/